name: Release Weekly

on:
  workflow_dispatch:

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Build and Release
      env:
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
        ZAP_RELEASE: 1
        ZAP_JAVA_VERSION: 17
        ZAP_WEEKLY_ADDONS_NO_TEST: ${{ vars.ZAP_WEEKLY_ADDONS_NO_TEST }}
        ZAP_WEEKLY_QUIET: ${{ vars.ZAP_WEEKLY_QUIET }}
      run: |
        chmod +x ./gradlew
        ls -lha gradlew
        ./gradlew "-Dorg.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m" :zap:createWeeklyRelease
